/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shared.models;

import org.junit.Test;
import static org.junit.Assert.*;

public class ArticleTest {
    @Test
    public void testArticleModelGetters() {
        Long id = 1L;
        String label = "Originals";
        String brand = "ADIDAS";
        String type = "SHOES";
        String description = "Desc";
        Double price = 3.4;
        Integer internalStock = 3;

        Article article = new Article(id, label, brand, type, description, price, internalStock);
        assertEquals(brand, ((Article) article).getBrand());
    }
}
